filter_words=['hasn', 'except', 'most', 'amongst', 'anyway', 'can', 'sometime', 'what', "wouldn't", "hadn't", 't',
              'something', 'beforehand', 'empty', 'moreover', 'nowhere', 'whom', 'almost', 'would', 'cannot', 'here',
              'ever', 'yourself', 'onto', 'hereby', 'why', 'a', 'whereupon', 'none', 'd', 'during', 'been', 'mostly',
              "aren't", 'thereafter', 'never', 'others', 'any', 'than', 'therein', 'under', 'once', 'theirs', 'yourselves',
              'even', 'there', 'next', 'below', 'am', 'formerly', 'our', 'it', "haven't", 'itself', 'along', 'no', 'to',
              "you're", 'are', 'just', 'them', 'needn', 'against', 'hundred', 'toward', "that'll", 'about', 'wouldn', 'that',
              'we', 'until', 'afterwards', 'up', 'latterly', "shouldn't", "you'd", 'an', 'is', 'off', 'anywhere', 'of',
              'shan', 'this', 'those', 'whither', 'indeed', 'nevertheless', 'whoever', 'himself', "shan't", 'nothing', 'too',
              'wherein', 'whence', 'shouldn', 'him', 'when', 'being', 'thereupon', 'mustn', 'where', 'anyone', 'another',
              'above', 'be', 'but', "hasn't", 'therefore', 'herself', 'these', "wasn't", 'whether', 'whole', 'first',
              'already', "doesn't", 'my', 'your', 'latter', 'myself', 'without', 've', 'between', 'somewhere', 'his',
              'll', "needn't", "should've", 'although', 'hadn', 'i', 'themselves', 'they', 'whereas', 'into', "she's", 'and',
              'their', 'doesn', 'everyone', 'aren', "isn't", 'again', 'noone', 'otherwise', 'over', 'were', 'then', 'how',
              'hereupon', "it's", 'may', "mightn't", 'same', 'more', 'thru', 'other', 'thence', 'enough', 'whenever',
              'meanwhile', 'which', "mustn't", 'yet', "you'll", 'used', 'thereby', 'anything', 'don', 'else', 'through',
              'by', 'wasn', 'within', 'won', 'now', 'ain', 'whereby', 'on', 'before', 'across', 'hereafter', 'however',
              'for', 'the', 'thus', 'with', 'y', 'you', 'also', 'unless', 'haven', 'whose', 'ours', 'could', 'as',
              'besides', 'both', "you've", 'beside', 'herein', 'whereafter', 'if', 'or', 's', 'isn', 'alone', 'wherever',
              'he', 'namely', 'o', 'least', 'she', 'in', 'weren', 'its', 'per', 'please', 'mightn', 'one', 'everything',
              'nobody', "couldn't", 'was', 'who', 'such', 'whatever', 'elsewhere', 'beyond', 'couldn', 'back', 'hers',
              'somehow', 'only', 'out', 'towards', 'not', 'hence', 'have', 'me', 'from', 'mine', 'didn', "don't", 'among',
              "won't", 'at', 'all', "didn't", 'her', 'neither', 'yours', 'after', 'down', 'throughout', 'due', 'around',
              'former', 'nor', 'while', 'must', "weren't", 'ourselves', 'upon', 'either', 'everywhere', 'anyhow', 'behind','left','right']
